
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar 20 2025 10:36:58 IST (Mar 20 2025 05:06:58 UTC)

// Verification Directory fv/single_port_ram 

module single_port_ram(clk, we, addr, din, dout);
  input clk, we;
  input [3:0] addr;
  input [7:0] din;
  output [7:0] dout;
  wire clk, we;
  wire [3:0] addr;
  wire [7:0] din;
  wire [7:0] dout;
  wire [7:0] \mem[14] ;
  wire [7:0] \mem[12] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[8] ;
  wire [7:0] \mem[10] ;
  wire [7:0] \mem[15] ;
  wire [7:0] \mem[11] ;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[13] ;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[9] ;
  wire [7:0] \mem[7] ;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141;
  DFFQX1 \dout_reg[1] (.CK (clk), .D (n_138), .Q (dout[1]));
  DFFQX1 \dout_reg[0] (.CK (clk), .D (n_137), .Q (dout[0]));
  DFFQX1 \dout_reg[3] (.CK (clk), .D (n_139), .Q (dout[3]));
  DFFQX1 \dout_reg[6] (.CK (clk), .D (n_140), .Q (dout[6]));
  DFFQX1 \dout_reg[7] (.CK (clk), .D (n_141), .Q (dout[7]));
  DFFQX1 \dout_reg[4] (.CK (clk), .D (n_135), .Q (dout[4]));
  DFFQX1 \dout_reg[5] (.CK (clk), .D (n_136), .Q (dout[5]));
  DFFQX1 \dout_reg[2] (.CK (clk), .D (n_134), .Q (dout[2]));
  OR2X1 g3135__2398(.A (n_132), .B (n_126), .Y (n_141));
  OR2X1 g3131__5107(.A (n_131), .B (n_122), .Y (n_140));
  OR2X1 g3136__6260(.A (n_133), .B (n_128), .Y (n_139));
  OR2X1 g3137__4319(.A (n_130), .B (n_125), .Y (n_138));
  OR2X1 g3134__8428(.A (n_129), .B (n_118), .Y (n_137));
  OR2X1 g3132__5526(.A (n_127), .B (n_121), .Y (n_136));
  OR2X1 g3138__6783(.A (n_119), .B (n_124), .Y (n_135));
  OR2X1 g3133__3680(.A (n_123), .B (n_120), .Y (n_134));
  NAND4XL g3143__1617(.A (n_106), .B (n_25), .C (n_27), .D (n_28), .Y
       (n_133));
  NAND4XL g3144__2802(.A (n_108), .B (n_31), .C (n_34), .D (n_36), .Y
       (n_132));
  NAND4XL g3145__1705(.A (n_45), .B (n_47), .C (n_48), .D (n_113), .Y
       (n_131));
  NAND4XL g3146__5122(.A (n_73), .B (n_83), .C (n_24), .D (n_112), .Y
       (n_130));
  NAND4XL g3140__8246(.A (n_110), .B (n_57), .C (n_65), .D (n_86), .Y
       (n_129));
  NAND4XL g3152__7098(.A (n_32), .B (n_37), .C (n_35), .D (n_91), .Y
       (n_128));
  NAND4XL g3142__6131(.A (n_70), .B (n_59), .C (n_58), .D (n_46), .Y
       (n_127));
  NAND4XL g3151__1881(.A (n_39), .B (n_40), .C (n_43), .D (n_42), .Y
       (n_126));
  NAND4XL g3153__5115(.A (n_26), .B (n_33), .C (n_29), .D (n_41), .Y
       (n_125));
  NAND4XL g3154__7482(.A (n_77), .B (n_98), .C (n_80), .D (n_99), .Y
       (n_124));
  NAND4XL g3139__4733(.A (n_49), .B (n_97), .C (n_87), .D (n_93), .Y
       (n_123));
  NAND4XL g3147__6161(.A (n_23), .B (n_96), .C (n_92), .D (n_88), .Y
       (n_122));
  NAND4XL g3148__9315(.A (n_101), .B (n_62), .C (n_60), .D (n_64), .Y
       (n_121));
  NAND4XL g3149__9945(.A (n_74), .B (n_61), .C (n_63), .D (n_66), .Y
       (n_120));
  NAND4XL g3141__2883(.A (n_67), .B (n_69), .C (n_71), .D (n_100), .Y
       (n_119));
  NAND4XL g3150__2346(.A (n_30), .B (n_44), .C (n_38), .D (n_68), .Y
       (n_118));
  SDFFQXL \mem_reg[14][4] (.CK (clk), .D (\mem[14] [4]), .SI (din[4]),
       .SE (n_103), .Q (\mem[14] [4]));
  SDFFQX1 \mem_reg[12][4] (.CK (clk), .D (\mem[12] [4]), .SI (din[4]),
       .SE (n_105), .Q (\mem[12] [4]));
  SDFFQXL \mem_reg[6][0] (.CK (clk), .D (\mem[6] [0]), .SI (din[0]),
       .SE (n_115), .Q (\mem[6] [0]));
  SDFFQXL \mem_reg[2][0] (.CK (clk), .D (\mem[2] [0]), .SI (din[0]),
       .SE (n_117), .Q (\mem[2] [0]));
  SDFFQXL \mem_reg[2][1] (.CK (clk), .D (\mem[2] [1]), .SI (din[1]),
       .SE (n_117), .Q (\mem[2] [1]));
  SDFFQXL \mem_reg[2][2] (.CK (clk), .D (\mem[2] [2]), .SI (din[2]),
       .SE (n_117), .Q (\mem[2] [2]));
  SDFFQXL \mem_reg[2][3] (.CK (clk), .D (\mem[2] [3]), .SI (din[3]),
       .SE (n_117), .Q (\mem[2] [3]));
  SDFFQXL \mem_reg[2][4] (.CK (clk), .D (\mem[2] [4]), .SI (din[4]),
       .SE (n_117), .Q (\mem[2] [4]));
  SDFFQXL \mem_reg[2][5] (.CK (clk), .D (\mem[2] [5]), .SI (din[5]),
       .SE (n_117), .Q (\mem[2] [5]));
  SDFFQXL \mem_reg[2][6] (.CK (clk), .D (\mem[2] [6]), .SI (din[6]),
       .SE (n_117), .Q (\mem[2] [6]));
  SDFFQXL \mem_reg[2][7] (.CK (clk), .D (\mem[2] [7]), .SI (din[7]),
       .SE (n_117), .Q (\mem[2] [7]));
  SDFFQX1 \mem_reg[4][0] (.CK (clk), .D (\mem[4] [0]), .SI (din[0]),
       .SE (n_116), .Q (\mem[4] [0]));
  SDFFQX1 \mem_reg[4][1] (.CK (clk), .D (\mem[4] [1]), .SI (din[1]),
       .SE (n_116), .Q (\mem[4] [1]));
  SDFFQX1 \mem_reg[4][2] (.CK (clk), .D (\mem[4] [2]), .SI (din[2]),
       .SE (n_116), .Q (\mem[4] [2]));
  SDFFQX1 \mem_reg[4][3] (.CK (clk), .D (\mem[4] [3]), .SI (din[3]),
       .SE (n_116), .Q (\mem[4] [3]));
  SDFFQX1 \mem_reg[4][4] (.CK (clk), .D (\mem[4] [4]), .SI (din[4]),
       .SE (n_116), .Q (\mem[4] [4]));
  SDFFQX1 \mem_reg[4][5] (.CK (clk), .D (\mem[4] [5]), .SI (din[5]),
       .SE (n_116), .Q (\mem[4] [5]));
  SDFFQX1 \mem_reg[4][6] (.CK (clk), .D (\mem[4] [6]), .SI (din[6]),
       .SE (n_116), .Q (\mem[4] [6]));
  SDFFQX1 \mem_reg[4][7] (.CK (clk), .D (\mem[4] [7]), .SI (din[7]),
       .SE (n_116), .Q (\mem[4] [7]));
  SDFFQXL \mem_reg[6][1] (.CK (clk), .D (\mem[6] [1]), .SI (din[1]),
       .SE (n_115), .Q (\mem[6] [1]));
  SDFFQXL \mem_reg[6][2] (.CK (clk), .D (\mem[6] [2]), .SI (din[2]),
       .SE (n_115), .Q (\mem[6] [2]));
  SDFFQXL \mem_reg[6][3] (.CK (clk), .D (\mem[6] [3]), .SI (din[3]),
       .SE (n_115), .Q (\mem[6] [3]));
  SDFFQXL \mem_reg[6][5] (.CK (clk), .D (\mem[6] [5]), .SI (din[5]),
       .SE (n_115), .Q (\mem[6] [5]));
  SDFFQXL \mem_reg[6][6] (.CK (clk), .D (\mem[6] [6]), .SI (din[6]),
       .SE (n_115), .Q (\mem[6] [6]));
  SDFFQXL \mem_reg[6][7] (.CK (clk), .D (\mem[6] [7]), .SI (din[7]),
       .SE (n_115), .Q (\mem[6] [7]));
  SDFFQX1 \mem_reg[8][0] (.CK (clk), .D (\mem[8] [0]), .SI (din[0]),
       .SE (n_114), .Q (\mem[8] [0]));
  SDFFQX1 \mem_reg[8][1] (.CK (clk), .D (\mem[8] [1]), .SI (din[1]),
       .SE (n_114), .Q (\mem[8] [1]));
  SDFFQX1 \mem_reg[8][2] (.CK (clk), .D (\mem[8] [2]), .SI (din[2]),
       .SE (n_114), .Q (\mem[8] [2]));
  SDFFQX1 \mem_reg[8][3] (.CK (clk), .D (\mem[8] [3]), .SI (din[3]),
       .SE (n_114), .Q (\mem[8] [3]));
  SDFFQX1 \mem_reg[8][4] (.CK (clk), .D (\mem[8] [4]), .SI (din[4]),
       .SE (n_114), .Q (\mem[8] [4]));
  SDFFQX1 \mem_reg[8][5] (.CK (clk), .D (\mem[8] [5]), .SI (din[5]),
       .SE (n_114), .Q (\mem[8] [5]));
  SDFFQX1 \mem_reg[8][6] (.CK (clk), .D (\mem[8] [6]), .SI (din[6]),
       .SE (n_114), .Q (\mem[8] [6]));
  SDFFQX1 \mem_reg[8][7] (.CK (clk), .D (\mem[8] [7]), .SI (din[7]),
       .SE (n_114), .Q (\mem[8] [7]));
  SDFFQXL \mem_reg[10][0] (.CK (clk), .D (\mem[10] [0]), .SI (din[0]),
       .SE (n_102), .Q (\mem[10] [0]));
  AOI222XL g3228__1666(.A0 (n_72), .A1 (\mem[15] [6]), .B0 (n_111), .B1
       (\mem[14] [6]), .C0 (dout[6]), .C1 (we), .Y (n_113));
  AOI222XL g3227__7410(.A0 (n_109), .A1 (\mem[11] [1]), .B0 (n_111),
       .B1 (\mem[14] [1]), .C0 (dout[1]), .C1 (we), .Y (n_112));
  AOI222XL g3226__6417(.A0 (dout[0]), .A1 (we), .B0 (n_109), .B1
       (\mem[11] [0]), .C0 (n_107), .C1 (\mem[0] [0]), .Y (n_110));
  AOI222XL g3229__5477(.A0 (dout[7]), .A1 (we), .B0 (n_109), .B1
       (\mem[11] [7]), .C0 (n_107), .C1 (\mem[0] [7]), .Y (n_108));
  AOI222XL g3230__2398(.A0 (n_109), .A1 (\mem[11] [3]), .B0 (we), .B1
       (dout[3]), .C0 (\mem[0] [3]), .C1 (n_107), .Y (n_106));
  SDFFQX1 \mem_reg[12][5] (.CK (clk), .D (\mem[12] [5]), .SI (din[5]),
       .SE (n_105), .Q (\mem[12] [5]));
  SDFFQX1 \mem_reg[12][6] (.CK (clk), .D (\mem[12] [6]), .SI (din[6]),
       .SE (n_105), .Q (\mem[12] [6]));
  SDFFQX1 \mem_reg[12][7] (.CK (clk), .D (\mem[12] [7]), .SI (din[7]),
       .SE (n_105), .Q (\mem[12] [7]));
  SDFFQXL \mem_reg[0][0] (.CK (clk), .D (din[0]), .SI (\mem[0] [0]),
       .SE (n_104), .Q (\mem[0] [0]));
  SDFFQXL \mem_reg[0][1] (.CK (clk), .D (din[1]), .SI (\mem[0] [1]),
       .SE (n_104), .Q (\mem[0] [1]));
  SDFFQXL \mem_reg[14][0] (.CK (clk), .D (\mem[14] [0]), .SI (din[0]),
       .SE (n_103), .Q (\mem[14] [0]));
  SDFFQXL \mem_reg[14][1] (.CK (clk), .D (\mem[14] [1]), .SI (din[1]),
       .SE (n_103), .Q (\mem[14] [1]));
  SDFFQXL \mem_reg[10][2] (.CK (clk), .D (\mem[10] [2]), .SI (din[2]),
       .SE (n_102), .Q (\mem[10] [2]));
  SDFFQXL \mem_reg[14][2] (.CK (clk), .D (\mem[14] [2]), .SI (din[2]),
       .SE (n_103), .Q (\mem[14] [2]));
  SDFFQXL \mem_reg[14][3] (.CK (clk), .D (\mem[14] [3]), .SI (din[3]),
       .SE (n_103), .Q (\mem[14] [3]));
  SDFFQXL \mem_reg[0][3] (.CK (clk), .D (din[3]), .SI (\mem[0] [3]),
       .SE (n_104), .Q (\mem[0] [3]));
  SDFFQXL \mem_reg[14][5] (.CK (clk), .D (\mem[14] [5]), .SI (din[5]),
       .SE (n_103), .Q (\mem[14] [5]));
  SDFFQXL \mem_reg[0][4] (.CK (clk), .D (din[4]), .SI (\mem[0] [4]),
       .SE (n_104), .Q (\mem[0] [4]));
  SDFFQXL \mem_reg[14][6] (.CK (clk), .D (\mem[14] [6]), .SI (din[6]),
       .SE (n_103), .Q (\mem[14] [6]));
  SDFFQXL \mem_reg[0][5] (.CK (clk), .D (din[5]), .SI (\mem[0] [5]),
       .SE (n_104), .Q (\mem[0] [5]));
  SDFFQXL \mem_reg[0][6] (.CK (clk), .D (din[6]), .SI (\mem[0] [6]),
       .SE (n_104), .Q (\mem[0] [6]));
  SDFFQXL \mem_reg[0][7] (.CK (clk), .D (din[7]), .SI (\mem[0] [7]),
       .SE (n_104), .Q (\mem[0] [7]));
  SDFFQXL \mem_reg[14][7] (.CK (clk), .D (\mem[14] [7]), .SI (din[7]),
       .SE (n_103), .Q (\mem[14] [7]));
  SDFFQXL \mem_reg[0][2] (.CK (clk), .D (din[2]), .SI (\mem[0] [2]),
       .SE (n_104), .Q (\mem[0] [2]));
  SDFFQXL \mem_reg[10][3] (.CK (clk), .D (\mem[10] [3]), .SI (din[3]),
       .SE (n_102), .Q (\mem[10] [3]));
  SDFFQXL \mem_reg[10][4] (.CK (clk), .D (\mem[10] [4]), .SI (din[4]),
       .SE (n_102), .Q (\mem[10] [4]));
  SDFFQXL \mem_reg[10][5] (.CK (clk), .D (\mem[10] [5]), .SI (din[5]),
       .SE (n_102), .Q (\mem[10] [5]));
  SDFFQXL \mem_reg[10][6] (.CK (clk), .D (\mem[10] [6]), .SI (din[6]),
       .SE (n_102), .Q (\mem[10] [6]));
  SDFFQXL \mem_reg[10][7] (.CK (clk), .D (\mem[10] [7]), .SI (din[7]),
       .SE (n_102), .Q (\mem[10] [7]));
  SDFFQX1 \mem_reg[12][0] (.CK (clk), .D (\mem[12] [0]), .SI (din[0]),
       .SE (n_105), .Q (\mem[12] [0]));
  SDFFQX1 \mem_reg[12][1] (.CK (clk), .D (\mem[12] [1]), .SI (din[1]),
       .SE (n_105), .Q (\mem[12] [1]));
  SDFFQX1 \mem_reg[12][2] (.CK (clk), .D (\mem[12] [2]), .SI (din[2]),
       .SE (n_105), .Q (\mem[12] [2]));
  SDFFQX1 \mem_reg[12][3] (.CK (clk), .D (\mem[12] [3]), .SI (din[3]),
       .SE (n_105), .Q (\mem[12] [3]));
  SDFFQXL \mem_reg[6][4] (.CK (clk), .D (\mem[6] [4]), .SI (din[4]),
       .SE (n_115), .Q (\mem[6] [4]));
  SDFFQXL \mem_reg[10][1] (.CK (clk), .D (\mem[10] [1]), .SI (din[1]),
       .SE (n_102), .Q (\mem[10] [1]));
  AOI22XL g3307__5107(.A0 (\mem[4] [5]), .A1 (n_76), .B0 (\mem[1] [5]),
       .B1 (n_75), .Y (n_101));
  AOI222XL g3224__6260(.A0 (n_107), .A1 (\mem[0] [4]), .B0 (we), .B1
       (dout[4]), .C0 (\mem[14] [4]), .C1 (n_111), .Y (n_100));
  AOI22X1 g3319__4319(.A0 (n_90), .A1 (\mem[2] [4]), .B0 (n_89), .B1
       (\mem[13] [4]), .Y (n_99));
  AOI22XL g3318__8428(.A0 (\mem[8] [4]), .A1 (n_95), .B0 (\mem[5] [4]),
       .B1 (n_94), .Y (n_98));
  AOI22X1 g3317__5526(.A0 (n_82), .A1 (\mem[6] [2]), .B0 (n_81), .B1
       (\mem[3] [2]), .Y (n_97));
  AOI22XL g3316__6783(.A0 (\mem[8] [6]), .A1 (n_95), .B0 (\mem[5] [6]),
       .B1 (n_94), .Y (n_96));
  AOI222XL g3223__3680(.A0 (n_107), .A1 (\mem[0] [2]), .B0 (we), .B1
       (dout[2]), .C0 (\mem[14] [2]), .C1 (n_111), .Y (n_93));
  AOI22XL g3314__1617(.A0 (\mem[12] [6]), .A1 (n_79), .B0 (\mem[9]
       [6]), .B1 (n_78), .Y (n_92));
  AOI22X1 g3326__2802(.A0 (n_90), .A1 (\mem[2] [3]), .B0 (n_89), .B1
       (\mem[13] [3]), .Y (n_91));
  AOI22X1 g3291__1705(.A0 (n_90), .A1 (\mem[2] [6]), .B0 (n_89), .B1
       (\mem[13] [6]), .Y (n_88));
  AOI22X1 g3315__5122(.A0 (n_85), .A1 (\mem[10] [2]), .B0 (n_84), .B1
       (\mem[7] [2]), .Y (n_87));
  AOI22X1 g3292__8246(.A0 (n_85), .A1 (\mem[10] [0]), .B0 (n_84), .B1
       (\mem[7] [0]), .Y (n_86));
  AOI22X1 g3293__7098(.A0 (n_82), .A1 (\mem[6] [1]), .B0 (n_81), .B1
       (\mem[3] [1]), .Y (n_83));
  AOI22XL g3294__6131(.A0 (\mem[12] [4]), .A1 (n_79), .B0 (\mem[9]
       [4]), .B1 (n_78), .Y (n_80));
  AOI22XL g3295__1881(.A0 (\mem[4] [4]), .A1 (n_76), .B0 (\mem[1] [4]),
       .B1 (n_75), .Y (n_77));
  AOI22XL g3313__5115(.A0 (\mem[4] [2]), .A1 (n_76), .B0 (\mem[1] [2]),
       .B1 (n_75), .Y (n_74));
  AOI22XL g3296__7482(.A0 (\mem[0] [1]), .A1 (n_107), .B0 (\mem[15]
       [1]), .B1 (n_72), .Y (n_73));
  AOI22X1 g3297__4733(.A0 (n_85), .A1 (\mem[10] [4]), .B0 (n_84), .B1
       (\mem[7] [4]), .Y (n_71));
  AOI22X1 g3312__6161(.A0 (n_111), .A1 (\mem[14] [5]), .B0 (n_109), .B1
       (\mem[11] [5]), .Y (n_70));
  AOI22X1 g3298__9315(.A0 (n_82), .A1 (\mem[6] [4]), .B0 (n_81), .B1
       (\mem[3] [4]), .Y (n_69));
  AOI22X1 g3299__9945(.A0 (n_90), .A1 (\mem[2] [0]), .B0 (n_89), .B1
       (\mem[13] [0]), .Y (n_68));
  AOI22XL g3300__2883(.A0 (\mem[11] [4]), .A1 (n_109), .B0 (\mem[15]
       [4]), .B1 (n_72), .Y (n_67));
  AOI22X1 g3311__2346(.A0 (n_90), .A1 (\mem[2] [2]), .B0 (n_89), .B1
       (\mem[13] [2]), .Y (n_66));
  AOI22X1 g3301__1666(.A0 (n_82), .A1 (\mem[6] [0]), .B0 (n_81), .B1
       (\mem[3] [0]), .Y (n_65));
  AOI22X1 g3302__7410(.A0 (n_90), .A1 (\mem[2] [5]), .B0 (n_89), .B1
       (\mem[13] [5]), .Y (n_64));
  AOI22XL g3303__6417(.A0 (\mem[12] [2]), .A1 (n_79), .B0 (\mem[9]
       [2]), .B1 (n_78), .Y (n_63));
  AOI22XL g3304__5477(.A0 (\mem[8] [5]), .A1 (n_95), .B0 (\mem[5] [5]),
       .B1 (n_94), .Y (n_62));
  AOI22XL g3305__2398(.A0 (\mem[8] [2]), .A1 (n_95), .B0 (\mem[5] [2]),
       .B1 (n_94), .Y (n_61));
  AOI22XL g3306__5107(.A0 (\mem[12] [5]), .A1 (n_79), .B0 (\mem[9]
       [5]), .B1 (n_78), .Y (n_60));
  AOI22X1 g3310__6260(.A0 (n_82), .A1 (\mem[6] [5]), .B0 (n_81), .B1
       (\mem[3] [5]), .Y (n_59));
  AOI22X1 g3309__4319(.A0 (n_85), .A1 (\mem[10] [5]), .B0 (n_84), .B1
       (\mem[7] [5]), .Y (n_58));
  AOI22X1 g3308__8428(.A0 (n_111), .A1 (\mem[14] [0]), .B0 (n_72), .B1
       (\mem[15] [0]), .Y (n_57));
  SDFFQXL \mem_reg[3][6] (.CK (clk), .D (din[6]), .SI (\mem[3] [6]),
       .SE (n_55), .Q (\mem[3] [6]));
  SDFFQXL \mem_reg[15][1] (.CK (clk), .D (din[1]), .SI (\mem[15] [1]),
       .SE (n_56), .Q (\mem[15] [1]));
  SDFFQXL \mem_reg[1][4] (.CK (clk), .D (din[4]), .SI (\mem[1] [4]),
       .SE (n_54), .Q (\mem[1] [4]));
  SDFFQXL \mem_reg[15][7] (.CK (clk), .D (din[7]), .SI (\mem[15] [7]),
       .SE (n_56), .Q (\mem[15] [7]));
  SDFFQXL \mem_reg[3][4] (.CK (clk), .D (din[4]), .SI (\mem[3] [4]),
       .SE (n_55), .Q (\mem[3] [4]));
  SDFFQXL \mem_reg[13][0] (.CK (clk), .D (din[0]), .SI (\mem[13] [0]),
       .SE (n_50), .Q (\mem[13] [0]));
  SDFFQXL \mem_reg[11][0] (.CK (clk), .D (din[0]), .SI (\mem[11] [0]),
       .SE (n_22), .Q (\mem[11] [0]));
  SDFFQXL \mem_reg[9][0] (.CK (clk), .D (din[0]), .SI (\mem[9] [0]),
       .SE (n_53), .Q (\mem[9] [0]));
  SDFFQXL \mem_reg[1][7] (.CK (clk), .D (din[7]), .SI (\mem[1] [7]),
       .SE (n_54), .Q (\mem[1] [7]));
  SDFFQXL \mem_reg[9][4] (.CK (clk), .D (din[4]), .SI (\mem[9] [4]),
       .SE (n_53), .Q (\mem[9] [4]));
  SDFFQXL \mem_reg[3][1] (.CK (clk), .D (din[1]), .SI (\mem[3] [1]),
       .SE (n_55), .Q (\mem[3] [1]));
  SDFFQXL \mem_reg[3][2] (.CK (clk), .D (din[2]), .SI (\mem[3] [2]),
       .SE (n_55), .Q (\mem[3] [2]));
  SDFFQXL \mem_reg[3][3] (.CK (clk), .D (din[3]), .SI (\mem[3] [3]),
       .SE (n_55), .Q (\mem[3] [3]));
  SDFFQXL \mem_reg[3][7] (.CK (clk), .D (din[7]), .SI (\mem[3] [7]),
       .SE (n_55), .Q (\mem[3] [7]));
  SDFFQXL \mem_reg[3][0] (.CK (clk), .D (din[0]), .SI (\mem[3] [0]),
       .SE (n_55), .Q (\mem[3] [0]));
  SDFFQXL \mem_reg[3][5] (.CK (clk), .D (din[5]), .SI (\mem[3] [5]),
       .SE (n_55), .Q (\mem[3] [5]));
  SDFFQXL \mem_reg[9][7] (.CK (clk), .D (din[7]), .SI (\mem[9] [7]),
       .SE (n_53), .Q (\mem[9] [7]));
  SDFFQXL \mem_reg[5][1] (.CK (clk), .D (din[1]), .SI (\mem[5] [1]),
       .SE (n_52), .Q (\mem[5] [1]));
  SDFFQXL \mem_reg[5][2] (.CK (clk), .D (din[2]), .SI (\mem[5] [2]),
       .SE (n_52), .Q (\mem[5] [2]));
  SDFFQXL \mem_reg[5][3] (.CK (clk), .D (din[3]), .SI (\mem[5] [3]),
       .SE (n_52), .Q (\mem[5] [3]));
  SDFFQXL \mem_reg[5][5] (.CK (clk), .D (din[5]), .SI (\mem[5] [5]),
       .SE (n_52), .Q (\mem[5] [5]));
  SDFFQXL \mem_reg[5][6] (.CK (clk), .D (din[6]), .SI (\mem[5] [6]),
       .SE (n_52), .Q (\mem[5] [6]));
  SDFFQXL \mem_reg[5][7] (.CK (clk), .D (din[7]), .SI (\mem[5] [7]),
       .SE (n_52), .Q (\mem[5] [7]));
  SDFFQXL \mem_reg[5][0] (.CK (clk), .D (din[0]), .SI (\mem[5] [0]),
       .SE (n_52), .Q (\mem[5] [0]));
  SDFFQXL \mem_reg[5][4] (.CK (clk), .D (din[4]), .SI (\mem[5] [4]),
       .SE (n_52), .Q (\mem[5] [4]));
  SDFFQXL \mem_reg[7][1] (.CK (clk), .D (din[1]), .SI (\mem[7] [1]),
       .SE (n_51), .Q (\mem[7] [1]));
  SDFFQXL \mem_reg[7][3] (.CK (clk), .D (din[3]), .SI (\mem[7] [3]),
       .SE (n_51), .Q (\mem[7] [3]));
  SDFFQXL \mem_reg[13][7] (.CK (clk), .D (din[7]), .SI (\mem[13] [7]),
       .SE (n_50), .Q (\mem[13] [7]));
  SDFFQXL \mem_reg[1][6] (.CK (clk), .D (din[6]), .SI (\mem[1] [6]),
       .SE (n_54), .Q (\mem[1] [6]));
  AOI22XL g3320__5526(.A0 (\mem[11] [2]), .A1 (n_109), .B0 (\mem[15]
       [2]), .B1 (n_72), .Y (n_49));
  AOI22X1 g3321__6783(.A0 (n_85), .A1 (\mem[10] [6]), .B0 (n_84), .B1
       (\mem[7] [6]), .Y (n_48));
  AOI22X1 g3322__3680(.A0 (n_82), .A1 (\mem[6] [6]), .B0 (n_81), .B1
       (\mem[3] [6]), .Y (n_47));
  AOI222XL g3225__1617(.A0 (n_107), .A1 (\mem[0] [5]), .B0 (we), .B1
       (dout[5]), .C0 (\mem[15] [5]), .C1 (n_72), .Y (n_46));
  AOI22XL g3323__2802(.A0 (\mem[0] [6]), .A1 (n_107), .B0 (\mem[11]
       [6]), .B1 (n_109), .Y (n_45));
  AOI22XL g3324__1705(.A0 (\mem[8] [0]), .A1 (n_95), .B0 (\mem[5] [0]),
       .B1 (n_94), .Y (n_44));
  AOI22XL g3325__5122(.A0 (\mem[12] [7]), .A1 (n_79), .B0 (\mem[9]
       [7]), .B1 (n_78), .Y (n_43));
  AOI22X1 g3327__8246(.A0 (n_90), .A1 (\mem[2] [7]), .B0 (n_89), .B1
       (\mem[13] [7]), .Y (n_42));
  AOI22X1 g3328__7098(.A0 (n_90), .A1 (\mem[2] [1]), .B0 (n_89), .B1
       (\mem[13] [1]), .Y (n_41));
  AOI22XL g3329__6131(.A0 (\mem[8] [7]), .A1 (n_95), .B0 (\mem[5] [7]),
       .B1 (n_94), .Y (n_40));
  AOI22XL g3330__1881(.A0 (\mem[4] [7]), .A1 (n_76), .B0 (\mem[1] [7]),
       .B1 (n_75), .Y (n_39));
  AOI22XL g3331__5115(.A0 (\mem[12] [0]), .A1 (n_79), .B0 (\mem[9]
       [0]), .B1 (n_78), .Y (n_38));
  AOI22XL g3332__7482(.A0 (\mem[8] [3]), .A1 (n_95), .B0 (\mem[5] [3]),
       .B1 (n_94), .Y (n_37));
  AOI22X1 g3333__4733(.A0 (n_85), .A1 (\mem[10] [7]), .B0 (n_84), .B1
       (\mem[7] [7]), .Y (n_36));
  AOI22XL g3334__6161(.A0 (\mem[12] [3]), .A1 (n_79), .B0 (\mem[9]
       [3]), .B1 (n_78), .Y (n_35));
  AOI22X1 g3335__9315(.A0 (n_82), .A1 (\mem[6] [7]), .B0 (n_81), .B1
       (\mem[3] [7]), .Y (n_34));
  AOI22XL g3336__9945(.A0 (\mem[8] [1]), .A1 (n_95), .B0 (\mem[5] [1]),
       .B1 (n_94), .Y (n_33));
  AOI22XL g3337__2883(.A0 (\mem[4] [3]), .A1 (n_76), .B0 (\mem[1] [3]),
       .B1 (n_75), .Y (n_32));
  AOI22X1 g3338__2346(.A0 (n_111), .A1 (\mem[14] [7]), .B0 (n_72), .B1
       (\mem[15] [7]), .Y (n_31));
  AOI22XL g3339__1666(.A0 (\mem[4] [0]), .A1 (n_76), .B0 (\mem[1] [0]),
       .B1 (n_75), .Y (n_30));
  AOI22XL g3340__7410(.A0 (\mem[12] [1]), .A1 (n_79), .B0 (\mem[9]
       [1]), .B1 (n_78), .Y (n_29));
  AOI22X1 g3341__6417(.A0 (n_85), .A1 (\mem[10] [3]), .B0 (n_84), .B1
       (\mem[7] [3]), .Y (n_28));
  AOI22X1 g3342__5477(.A0 (n_82), .A1 (\mem[6] [3]), .B0 (n_81), .B1
       (\mem[3] [3]), .Y (n_27));
  AOI22XL g3343__2398(.A0 (\mem[4] [1]), .A1 (n_76), .B0 (\mem[1] [1]),
       .B1 (n_75), .Y (n_26));
  AOI22X1 g3344__5107(.A0 (n_111), .A1 (\mem[14] [3]), .B0 (n_72), .B1
       (\mem[15] [3]), .Y (n_25));
  AOI22X1 g3345__6260(.A0 (n_85), .A1 (\mem[10] [1]), .B0 (n_84), .B1
       (\mem[7] [1]), .Y (n_24));
  AOI22XL g3346__4319(.A0 (\mem[4] [6]), .A1 (n_76), .B0 (\mem[1] [6]),
       .B1 (n_75), .Y (n_23));
  SDFFQXL \mem_reg[15][5] (.CK (clk), .D (din[5]), .SI (\mem[15] [5]),
       .SE (n_56), .Q (\mem[15] [5]));
  SDFFQXL \mem_reg[1][0] (.CK (clk), .D (din[0]), .SI (\mem[1] [0]),
       .SE (n_54), .Q (\mem[1] [0]));
  SDFFQXL \mem_reg[15][6] (.CK (clk), .D (din[6]), .SI (\mem[15] [6]),
       .SE (n_56), .Q (\mem[15] [6]));
  SDFFQXL \mem_reg[1][1] (.CK (clk), .D (din[1]), .SI (\mem[1] [1]),
       .SE (n_54), .Q (\mem[1] [1]));
  SDFFQXL \mem_reg[1][2] (.CK (clk), .D (din[2]), .SI (\mem[1] [2]),
       .SE (n_54), .Q (\mem[1] [2]));
  SDFFQXL \mem_reg[1][3] (.CK (clk), .D (din[3]), .SI (\mem[1] [3]),
       .SE (n_54), .Q (\mem[1] [3]));
  SDFFQXL \mem_reg[1][5] (.CK (clk), .D (din[5]), .SI (\mem[1] [5]),
       .SE (n_54), .Q (\mem[1] [5]));
  SDFFQXL \mem_reg[9][6] (.CK (clk), .D (din[6]), .SI (\mem[9] [6]),
       .SE (n_53), .Q (\mem[9] [6]));
  SDFFQXL \mem_reg[11][1] (.CK (clk), .D (din[1]), .SI (\mem[11] [1]),
       .SE (n_22), .Q (\mem[11] [1]));
  SDFFQXL \mem_reg[9][5] (.CK (clk), .D (din[5]), .SI (\mem[9] [5]),
       .SE (n_53), .Q (\mem[9] [5]));
  SDFFQXL \mem_reg[11][2] (.CK (clk), .D (din[2]), .SI (\mem[11] [2]),
       .SE (n_22), .Q (\mem[11] [2]));
  SDFFQXL \mem_reg[11][3] (.CK (clk), .D (din[3]), .SI (\mem[11] [3]),
       .SE (n_22), .Q (\mem[11] [3]));
  SDFFQXL \mem_reg[11][6] (.CK (clk), .D (din[6]), .SI (\mem[11] [6]),
       .SE (n_22), .Q (\mem[11] [6]));
  SDFFQXL \mem_reg[11][5] (.CK (clk), .D (din[5]), .SI (\mem[11] [5]),
       .SE (n_22), .Q (\mem[11] [5]));
  SDFFQXL \mem_reg[7][6] (.CK (clk), .D (din[6]), .SI (\mem[7] [6]),
       .SE (n_51), .Q (\mem[7] [6]));
  SDFFQXL \mem_reg[9][1] (.CK (clk), .D (din[1]), .SI (\mem[9] [1]),
       .SE (n_53), .Q (\mem[9] [1]));
  SDFFQXL \mem_reg[13][1] (.CK (clk), .D (din[1]), .SI (\mem[13] [1]),
       .SE (n_50), .Q (\mem[13] [1]));
  SDFFQXL \mem_reg[13][2] (.CK (clk), .D (din[2]), .SI (\mem[13] [2]),
       .SE (n_50), .Q (\mem[13] [2]));
  SDFFQXL \mem_reg[13][3] (.CK (clk), .D (din[3]), .SI (\mem[13] [3]),
       .SE (n_50), .Q (\mem[13] [3]));
  SDFFQXL \mem_reg[9][2] (.CK (clk), .D (din[2]), .SI (\mem[9] [2]),
       .SE (n_53), .Q (\mem[9] [2]));
  SDFFQXL \mem_reg[13][5] (.CK (clk), .D (din[5]), .SI (\mem[13] [5]),
       .SE (n_50), .Q (\mem[13] [5]));
  SDFFQXL \mem_reg[13][6] (.CK (clk), .D (din[6]), .SI (\mem[13] [6]),
       .SE (n_50), .Q (\mem[13] [6]));
  SDFFQXL \mem_reg[7][4] (.CK (clk), .D (din[4]), .SI (\mem[7] [4]),
       .SE (n_51), .Q (\mem[7] [4]));
  SDFFQXL \mem_reg[7][7] (.CK (clk), .D (din[7]), .SI (\mem[7] [7]),
       .SE (n_51), .Q (\mem[7] [7]));
  SDFFQXL \mem_reg[9][3] (.CK (clk), .D (din[3]), .SI (\mem[9] [3]),
       .SE (n_53), .Q (\mem[9] [3]));
  SDFFQXL \mem_reg[7][5] (.CK (clk), .D (din[5]), .SI (\mem[7] [5]),
       .SE (n_51), .Q (\mem[7] [5]));
  SDFFQXL \mem_reg[15][0] (.CK (clk), .D (din[0]), .SI (\mem[15] [0]),
       .SE (n_56), .Q (\mem[15] [0]));
  SDFFQXL \mem_reg[15][2] (.CK (clk), .D (din[2]), .SI (\mem[15] [2]),
       .SE (n_56), .Q (\mem[15] [2]));
  SDFFQXL \mem_reg[15][3] (.CK (clk), .D (din[3]), .SI (\mem[15] [3]),
       .SE (n_56), .Q (\mem[15] [3]));
  SDFFQXL \mem_reg[13][4] (.CK (clk), .D (din[4]), .SI (\mem[13] [4]),
       .SE (n_50), .Q (\mem[13] [4]));
  SDFFQXL \mem_reg[7][2] (.CK (clk), .D (din[2]), .SI (\mem[7] [2]),
       .SE (n_51), .Q (\mem[7] [2]));
  SDFFQXL \mem_reg[11][7] (.CK (clk), .D (din[7]), .SI (\mem[11] [7]),
       .SE (n_22), .Q (\mem[11] [7]));
  SDFFQXL \mem_reg[11][4] (.CK (clk), .D (din[4]), .SI (\mem[11] [4]),
       .SE (n_22), .Q (\mem[11] [4]));
  SDFFQXL \mem_reg[7][0] (.CK (clk), .D (din[0]), .SI (\mem[7] [0]),
       .SE (n_51), .Q (\mem[7] [0]));
  SDFFQXL \mem_reg[15][4] (.CK (clk), .D (din[4]), .SI (\mem[15] [4]),
       .SE (n_56), .Q (\mem[15] [4]));
  NOR2X1 g3357__8428(.A (n_16), .B (n_11), .Y (n_115));
  NAND2X1 g3373__5526(.A (n_21), .B (n_18), .Y (n_104));
  CLKAND2X2 g3375__6783(.A (n_21), .B (n_20), .Y (n_116));
  CLKAND2X2 g3377__3680(.A (n_21), .B (n_17), .Y (n_114));
  CLKAND2X2 g3372__1617(.A (n_21), .B (n_14), .Y (n_105));
  AND2X1 g3347__2802(.A (n_19), .B (n_20), .Y (n_94));
  AND2X1 g3348__1705(.A (n_19), .B (n_18), .Y (n_75));
  AND2X1 g3353__5122(.A (n_19), .B (n_17), .Y (n_78));
  NOR2X1 g3363__8246(.A (n_13), .B (n_15), .Y (n_81));
  NOR2X1 g3358__7098(.A (n_16), .B (n_10), .Y (n_102));
  NOR2X1 g3361__6131(.A (n_16), .B (n_15), .Y (n_117));
  NOR2X1 g3362__1881(.A (n_16), .B (n_12), .Y (n_103));
  AND2X1 g3354__5115(.A (n_19), .B (n_14), .Y (n_89));
  NOR2X1 g3368__7482(.A (n_13), .B (n_12), .Y (n_72));
  NOR2X1 g3369__4733(.A (n_13), .B (n_11), .Y (n_84));
  NOR2X1 g3370__6161(.A (n_13), .B (n_10), .Y (n_109));
  NOR2X1 g3349__9315(.A (n_8), .B (n_10), .Y (n_85));
  NAND2X1 g3374__9945(.A (n_9), .B (n_14), .Y (n_56));
  NAND2X1 g3376__2883(.A (n_9), .B (n_20), .Y (n_51));
  NAND2X1 g3378__2346(.A (n_9), .B (n_18), .Y (n_55));
  NAND2X1 g3371__1666(.A (n_9), .B (n_17), .Y (n_22));
  NOR2X1 g3350__7410(.A (n_8), .B (n_15), .Y (n_90));
  NOR2X1 g3351__6417(.A (n_8), .B (n_11), .Y (n_82));
  NOR2X1 g3352__5477(.A (n_8), .B (n_12), .Y (n_111));
  NOR2X1 g3364__2398(.A (n_6), .B (n_10), .Y (n_95));
  NAND2X1 g3356__5107(.A (n_7), .B (n_17), .Y (n_53));
  NAND2X1 g3359__6260(.A (n_7), .B (n_20), .Y (n_52));
  NAND2X1 g3360__4319(.A (n_7), .B (n_18), .Y (n_54));
  NAND2X1 g3355__8428(.A (n_7), .B (n_14), .Y (n_50));
  NOR2X1 g3365__5526(.A (n_6), .B (n_15), .Y (n_107));
  NOR2X1 g3366__6783(.A (n_6), .B (n_11), .Y (n_76));
  NOR2X1 g3367__3680(.A (n_6), .B (n_12), .Y (n_79));
  NAND2XL g3381__1617(.A (n_4), .B (addr[1]), .Y (n_16));
  OR2X1 g3383__2802(.A (n_5), .B (n_3), .Y (n_13));
  NOR2XL g3384__1705(.A (n_5), .B (addr[1]), .Y (n_19));
  AND2X1 g3386__5122(.A (n_4), .B (n_3), .Y (n_21));
  NOR2X1 g3379__8246(.A (n_2), .B (addr[1]), .Y (n_7));
  NOR2X1 g3380__7098(.A (n_2), .B (n_3), .Y (n_9));
  NAND2XL g3382__6131(.A (n_1), .B (addr[1]), .Y (n_8));
  NAND2XL g3385__1881(.A (n_1), .B (n_3), .Y (n_6));
  NAND2XL g3390__5115(.A (n_0), .B (addr[0]), .Y (n_5));
  CLKINVX1 g3387(.A (n_12), .Y (n_14));
  CLKINVX1 g3392(.A (n_11), .Y (n_20));
  NOR2XL g3395__7482(.A (n_0), .B (addr[0]), .Y (n_4));
  CLKINVX1 g3394(.A (n_10), .Y (n_17));
  CLKINVX1 g3393(.A (n_18), .Y (n_15));
  NAND2XL g3388__4733(.A (we), .B (addr[0]), .Y (n_2));
  NOR2XL g3389__6161(.A (we), .B (addr[0]), .Y (n_1));
  NAND2X1 g3391__9315(.A (addr[2]), .B (addr[3]), .Y (n_12));
  NAND2BX1 g3396__9945(.AN (addr[3]), .B (addr[2]), .Y (n_11));
  NOR2X1 g3397__2883(.A (addr[3]), .B (addr[2]), .Y (n_18));
  NAND2BX1 g3398__2346(.AN (addr[2]), .B (addr[3]), .Y (n_10));
  INVXL g3399(.A (we), .Y (n_0));
  CLKINVX1 g3400(.A (addr[1]), .Y (n_3));
endmodule

